version: '2'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  app:
    container_name: node-app
    build: .
    links:
      - redis
    ports:
      - '5000:5000'
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=development
      - PORT=5000
    command:
    sh -c 'npm i && node dist/index.js'
